### ISSUE TITLE
Not able to fetch suggestions/autocorrect capabilities

### ISSUE THREAD

**Issue by thegravityguy** [wingedrasengan927/lexical-medium-clone#3]
Hi Im trying to use the editor in the playground environment. However not able to access any AI capabilities

<img width="714" alt="image" src="https://github.com/wingedrasengan927/medium-ai/assets/170085299/1a4d0d16-addc-4f71-8875-84bd4efacefd">

Not sure if im operating the tool wrong or if theres some other issue at hand here.

**Comment by wingedrasengan927** [comment]
AI doesn't work in the playground environment as you would need an openai api key
